window.siteSearchIndex = [
  { path: 'asia.html', title: 'Asia Military', snippet: 'Information and resources about the Asia Military.' },
  { path: 'asian_military/vc01.html', title: 'Chinese Robot (VC01)', snippet: 'Information about the Chinese Robot (VC01) used by the Chinese Military.' },
  { path: 'asian_military/xsl.html', title: 'Slot Machine (XSL)', snippet: 'Information about the Slot Machine (XSL) used by the Japan Military.' },
  { path: 'eu_military/d4285.html', title: 'Dutch Navy Stanag-4285', snippet: 'Information about station Dutch Navy Stanag-4285' },
  { path: 'eu_military/f9tm.html', title: 'F9TM', snippet: 'Information about station F9TM' },
  { path: 'eu_military/fav22.html', title: 'FAV22', snippet: 'Information about station FAV22' },
  { path: 'eu_military/ndh.html', title: 'Navy Den Helder "De Kooy"', snippet: 'Information about station Navy Den Helder' },
  { path: 'eu_military/obtb.html', title: 'One Beep, Two Beeps', snippet: 'Information about station One Beep, Two Beeps' },
  { path: 'eu_military/pbb.html', title: 'PBB Den Helder', snippet: 'Information about station PBB Den Helder' },
  { path: 'eu_military/pbb4285.html', title: 'PBB Stanag-4285', snippet: 'Information about station PBB Stanag-4285' },
  { path: 'eu_military/pbbpcb-warship.html', title: 'PBB / PCB Warship', snippet: 'Information about station PBB / PCB Warship' },
  { path: 'eu_military/pbv.html', title: 'PVB NAS Valkenburg', snippet: 'Information about station PVB NAS Valkenburg' },
  { path: 'eu_military/pcb.html', title: 'PCB Goeree Island', snippet: 'Information about station PCB Goeree Island' },
  { path: 'eu_military/pcb4285.html', title: 'PCB Stanag-4285', snippet: 'Information about station PCB Stanag-4285' },
  { path: 'eu_military/pjc.html', title: 'PJC NRN Hato Curacao (Counter-Narco OPS)', snippet: 'Information about station PJC NRN Hato Curacao (Counter-Narco OPS)' },
  { path: 'eu_military/pjk.html', title: 'PJK Suffisant Curacao (ASW Operations)', snippet: 'Information about station PJK Suffisant Curacao (ASW Operations)' },
  { path: 'eu_military/unid13550.html', title: 'UNID 13550', snippet: 'Information about station UNID 13550' },
  { path: 'eu_military/x6853.html', title: 'XF Faders / XM Whales', snippet: 'Information about station XF Faders / XM Whales' },
  { path: 'europe.html', title: 'European Military', snippet: 'Information and resources about the European Military.' },
  { path: 'googlefe4cd57006ece8b9.html', title: 'googlefe4cd57006ece8b9', snippet: 'googlefe4cd57006ece8b9' },
  { path: 'index.html', title: '🏳‍🌈 Signabroam Shortwave Wiki', snippet: 'A wiki dedicated to providing information and resources about the Signabroam Shortwave radio.' },
  { path: 'military/03394.html', title: 'Unit 03394', snippet: 'Information about Unit 03394' },
  { path: 'military/14108.html', title: 'Unit 14108', snippet: 'Information about Unit 14108' },
  { path: 'military/3027.html', title: 'Unit 3027', snippet: 'Information about Unit 3027' },
  { path: 'military/31895.html', title: 'Unit 31895', snippet: 'Information about Unit 31895' },
  { path: 'military/32982.html', title: 'Unit 32982', snippet: 'Information about Unit 32982' },
  { path: 'military/34017.html', title: 'Unit 34017', snippet: 'Information about Unit 34017' },
  { path: 'military/41516.html', title: 'Unit 41516', snippet: 'Information about Unit 41516' },
  { path: 'military/43431.html', title: 'Unit 43431', snippet: 'Information about Unit 43431' },
  { path: 'military/49383.html', title: 'Unit 49383', snippet: 'Information about Unit 49383' },
  { path: 'military/52015.html', title: 'Unit 52015', snippet: 'Information about Unit 52015' },
  { path: 'military/52478.html', title: 'Unit 52478', snippet: 'Information about Unit 52478' },
  { path: 'military/52929.html', title: 'Units 52929', snippet: 'Information about Units 52929' },
  { path: 'military/5583.html', title: 'Unit 5583', snippet: 'Information about Unit 5583' },
  { path: 'military/56202.html', title: 'Unit 56202 / 40129-P', snippet: 'Information about Unit 56202 / 40129-P' },
  { path: 'military/56653.html', title: 'Unit 56653', snippet: 'Information about Unit 56653' },
  { path: 'military/59802.html', title: 'Unit 59802', snippet: 'Information about Unit 59802' },
  { path: 'military/71380.html', title: 'Unit 71380', snippet: 'Information about Unit 71380' },
  { path: 'military/73570.html', title: 'Unit 73570 / 03353', snippet: 'Information about Unit 73570 / 03353' },
  { path: 'military/77073.html', title: 'Unit 77073', snippet: 'Information about Unit 77073' },
  { path: 'military/83320.html', title: 'Unit 83320', snippet: 'Information about Unit 83320' },
  { path: 'military/95043.html', title: 'Unit 95043', snippet: 'Information about Unit 95043' },
  { path: 'military/Pikhta26.html', title: 'Pikhta26', snippet: 'Information about station Pikhta26' },
  { path: 'military/S4467.html', title: 'S4467', snippet: 'Information about station S4467' },
  { path: 'military/airhorn.html', title: 'The Air Horn', snippet: 'Information about station The Air Horn' },
  { path: 'military/alarm.html', title: 'The Alarm', snippet: 'Information about station The Alarm' },
  { path: 'military/arbat50.html', title: 'Arbat50', snippet: 'Information about station Arbat50' },
  { path: 'military/baron78.html', title: 'Baron78', snippet: 'Information about station Baron78' },
  { path: 'military/bereza2.html', title: 'Bereza2', snippet: 'Information about station Bereza2' },
  { path: 'military/berkut24.html', title: 'Berkut24', snippet: 'Information about station Berkut24' },
  { path: 'military/buzzer.html', title: 'The Buzzer', snippet: 'Information about station The Buzzer' },
  { path: 'military/cw/lra/lra.html', title: 'LRA Air Force', snippet: 'Information about the Long-Range Aviation Air Force network' },
  { path: 'military/cw/lra/ricarj.html', title: 'RICARJ', snippet: 'Information about station RICARJ' },
  { path: 'military/cw/monolith/596e.html', title: '596E', snippet: 'Information about station 596E' },
  { path: 'military/cw/monolith/cejx.html', title: 'CEJX', snippet: 'Information about station CEJX' },
  { path: 'military/cw/monolith/iq4o.html', title: 'IQ4O', snippet: 'Information about station IQ4O' },
  { path: 'military/cw/monolith/kufi.html', title: 'KUFI', snippet: 'Information about station KUFI' },
  { path: 'military/cw/monolith/la8k.html', title: 'LA8K', snippet: 'Information about station LA8K' },
  { path: 'military/cw/monolith/mdv.html', title: 'MDV', snippet: 'Information about station MDV' },
  { path: 'military/cw/monolith/pz4r.html', title: 'PZ4R', snippet: 'Information about station PZ4R' },
  { path: 'military/cw/monolith/rea4.html', title: 'REA4', snippet: 'Information about station REA4' },
  { path: 'military/cw/monolith/wegi.html', title: 'WEGI', snippet: 'Information about station WEGI' },
  { path: 'military/cw/monolith/xhop.html', title: 'XHOP', snippet: 'Information about station XHOP' },
  { path: 'military/davlenie.html', title: 'Davlenie', snippet: 'Information about station Davlenie' },
  { path: 'military/dmarker.html', title: 'The D Marker', snippet: 'Information about the D Marker' },
  { path: 'military/duplet16.html', title: 'Duplet16', snippet: 'Information about station Duplet16' },
  { path: 'military/dynatron.html', title: 'Dynatron Communication Hub', snippet: 'Information about the Dynatron Communication Hub' },
  { path: 'military/fgkt.html', title: 'FGKT', snippet: 'Information about station FGKT' },
  { path: 'military/goose.html', title: 'The Goose', snippet: 'Information about station The Goose' },
  { path: 'military/goretz81.html', title: 'Goretz81', snippet: 'Information about station Goretz81' },
  { path: 'military/kasta.html', title: 'Kasta', snippet: 'Information about station Kasta' },
  { path: 'military/katok65.html', title: 'Katok65', snippet: 'Information about station Katok65' },
  { path: 'military/kerropip.html', title: 'The Kerro Pip Russian Network', snippet: 'Information about station The Kerro Pip Russian Network' },
  { path: 'military/klarnetist.html', title: 'Klarnetist', snippet: 'Information about station Klarnetist' },
  { path: 'military/korsar.html', title: 'Korsar', snippet: 'Information about station Korsar' },
  { path: 'military/kroket21.html', title: 'Kroket21', snippet: 'Information about station Kroket21' },
  { path: 'military/lad-ya.html', title: 'Lad\'ya', snippet: 'Information about station Lad' },
  { path: 'military/magnetron.html', title: 'Magnetron', snippet: 'Information about station Magnetron' },
  { path: 'military/mikron79.html', title: 'Mikron79', snippet: 'Information about station Mikron79' },
  { path: 'military/modem/cis12.html', title: 'cis12', snippet: 'cis12' },
  { path: 'military/musicalpip.html', title: 'The Russian Musical Pip', snippet: 'Information about station The Russian Musical Pip' },
  { path: 'military/nrn.html', title: 'Northern Russian Network', snippet: 'Information about station Northern Russian Network' },
  { path: 'military/patron79.html', title: 'Patron79', snippet: 'Information about station Patron79' },
  { path: 'military/pip.html', title: 'The Pip', snippet: 'Information about station The Pip' },
  { path: 'military/platoon.html', title: '★= Platoon MN - *50=★', snippet: 'Information about ★= Platoon MN - *50=★' },
  { path: 'military/polis.html', title: 'Polis', snippet: 'Information about station Polis' },
  { path: 'military/polotno.html', title: 'Polotno', snippet: 'Information about station Polotno' },
  { path: 'military/proselok.html', title: 'Proselok', snippet: 'Information about station Proselok' },
  { path: 'military/rmarker.html', title: 'The R Marker', snippet: 'Information about station The R Marker' },
  { path: 'military/s12035.html', title: 'S12035', snippet: 'Information about station S12035' },
  { path: 'military/s39504960.html', title: 's39504960', snippet: 's39504960' },
  { path: 'military/s4468.html', title: 'S4468', snippet: 'Information about station S4468' },
  { path: 'military/s4574.html', title: 'S4574', snippet: 'Information about station S4574' },
  { path: 'military/s5826.html', title: 'S5826', snippet: 'Information about station S5826' },
  { path: 'military/s5959.html', title: 'S5959', snippet: 'Information about station S5959' },
  { path: 'military/s9062.html', title: 'S9062', snippet: 'Information about station S9062' },
  { path: 'military/sosna2.html', title: 'Sosna2', snippet: 'Information about station Sosna2' },
  { path: 'military/squeakywheel.html', title: 'The Squeaky Wheel', snippet: 'Information about station The Squeaky Wheel' },
  { path: 'military/srn.html', title: 'Southern Russian Network', snippet: 'Information about station Southern Russian Network' },
  { path: 'military/tmarker.html', title: 'The T Marker', snippet: 'Information about station The T Marker' },
  { path: 'military/topol.html', title: 'Topol', snippet: 'Information about station Topol (3950/4960 kHz)' },
  { path: 'military/torez91.html', title: 'Torez91', snippet: 'Information about station Torez91' },
  { path: 'military/vcpt.html', title: 'Voice Communication Propagation Test', snippet: 'Information about station Voice Communication Propagation Test' },
  { path: 'military/vega.html', title: 'Vega', snippet: 'Information about station Vega' },
  { path: 'military/vetka31.html', title: 'Vetka31', snippet: 'Information about station Vetka31' },
  { path: 'military/xmwf.html', title: 'The Russian XM Whales Feedback', snippet: 'Information about station The Russian XM Whales Feedback' },
  { path: 'military/zaliv52.html', title: 'Zaliv52', snippet: 'Information about station Zaliv52' },
  { path: 'modems.html', title: 'Worldwide Modems', snippet: 'Information and resources about worldwide modems.' },
  { path: 'modems/cis112.html', title: 'CIS-112', snippet: 'Information about station CIS-112' },
  { path: 'modems/cis12.html', title: 'CIS-12', snippet: 'Information about station CIS-12' },
  { path: 'modems/cis3.html', title: 'CIS-3', snippet: 'Information about station CIS-3' },
  { path: 'modems/cis4.html', title: 'CIS-4', snippet: 'Information about station CIS-4' },
  { path: 'more/bandplan.html', title: 'Shortwave Band Plan', snippet: 'A comprehensive overview of the shortwave radio spectrum, including frequency ranges and typical uses for each band.' },
  { path: 'more/ids.html', title: 'Signabroam ID', snippet: 'A wiki dedicated to providing information and resources about the Signabroam Shortwave radio.' },
  { path: 'more/rus_mil/message_formats.html', title: 'Russian Military Message Formats - Radio Communication Urgency Categories', snippet: 'Urgency Categories and Transmission Protocol' },
  { path: 'more/rus_mil/monolith-theoretical.html', title: 'HF Monolith Network - Theoretical Model', snippet: 'Global overview of the theoretical structure and communication flow of the Monolith HF network, based on observed signal patterns and public monitoring data.' },
  { path: 'more/rus_mil/rusmil_coms_in_leningrad.html', title: 'Russian Communication Hubs in Leningrad Region', snippet: 'An interesting event occurred during UVB-76 (The Buzzer) monitoring. A woman\'s voice suddenly appeared on top of the buzzer marker transmission:' },
  { path: 'more/stationschedule.html', title: 'Signabroam Station Scheduler', snippet: '📅 Station Scheduler' },
  { path: 'numbers-stations.html', title: 'Numbers Stations', snippet: 'Information and resources about numbers stations.' },
  { path: 'numbers-stations/english/e06.html', title: 'English Man (E06)', snippet: 'Information about the English Man (E06) numbers station.' },
  { path: 'numbers-stations/morse/fl.html', title: 'FL Numbers Station', snippet: 'Information about the FL Numbers Station' },
  { path: 'numbers-stations/morse/ici.html', title: 'ICI Numbers Station', snippet: 'Information about the ICI Numbers Station' },
  { path: 'numbers-stations/morse/m01.html', title: 'M01 - Signabroam Shortwave Wiki', snippet: 'Information about the M01 numbers station.' },
  { path: 'numbers-stations/morse/m12.html', title: 'M12 - Signabroam Shortwave Wiki', snippet: 'Information about the M12 numbers station.' },
  { path: 'numbers-stations/morse/m14.html', title: 'M14 - Signabroam Shortwave Wiki', snippet: 'Information about the M14 numbers station.' },
  { path: 'numbers-stations/morse/msk.html', title: 'MSK Numbers Station', snippet: 'Information about the MSK Numbers Station' },
  { path: 'pirate.html', title: 'Pirate Stations', snippet: 'Information and resources about pirate radio stations.' },
  { path: 'pirate/4525.html', title: '4525 kHz Buzzer', snippet: 'Information about station 4525 kHz Buzzer' },
  { path: 'pirate/6660.html', title: 'The 45m Band', snippet: 'Information about the 45m band and the stations that transmit on it.' },
  { path: 'pirate/akula56.html', title: 'Akula56', snippet: 'Information about station Akula56' },
  { path: 'pirate/argus.html', title: 'Radio Argus', snippet: 'Information about station Radio Argus' },
  { path: 'pirate/augusta.html', title: 'Radio Augusta Int', snippet: 'Information about station Radio Augusta Int' },
  { path: 'pirate/dickbulger.html', title: 'Dick Bulger Radio', snippet: 'Information about Dick Bulger Radio' },
  { path: 'pirate/m4j.html', title: 'M4J - Mystery 4 Joy', snippet: 'Information about station M4J - Mystery 4 Joy' },
  { path: 'pirate/miamigo.html', title: 'Radio Mi Amigo Int', snippet: 'Information about station Radio Mi Amigo Int' },
  { path: 'pirate/pamela.html', title: 'Radio Pamela', snippet: 'Information about station Radio Pamela' },
  { path: 'pirate/radiozand.html', title: 'Radio Zand', snippet: 'Information about station Radio Zand' },
  { path: 'pirate/rojxam.html', title: 'Radio ROJX AM', snippet: 'Information about station Radio ROJX AM' },
  { path: 'pirate/rwi.html', title: 'Radio Wave Int', snippet: 'Information about station Radio Wave Int' },
  { path: 'pirate/starlight.html', title: 'Radio Starlight', snippet: 'Information about station Radio Starlight' },
  { path: 'pirate/stern.html', title: 'Radio Stern', snippet: 'Information about station Radio Stern' },
  { path: 'pirate/tsvef.html', title: 'TsVEF', snippet: 'Information about station TsVEF' },
  { path: 'pirate/zeppelin.html', title: 'Zeppelin Radio', snippet: 'Information about station Zeppelin Radio' },
  { path: 'rusmil.html', title: 'Russian Military', snippet: 'Information and resources about the Russian Military.' },
  { path: 'time-stations.html', title: 'World wide Time Stations', snippet: 'Information and resources about world wide time stations.' },
  { path: 'time_stations/ALS162.html', title: 'ALS162 - Signabroam Shortwave Wiki', snippet: 'Information about station ALS162.' },
  { path: 'time_stations/BPC.html', title: 'BPC - Signabroam Shortwave Wiki', snippet: 'Information about station BPC' },
  { path: 'time_stations/BPM.html', title: 'BPM - Signabroam Shortwave Wiki', snippet: 'Information about station BPM' },
  { path: 'time_stations/BSF.html', title: 'BSF - Signabroam Shortwave Wiki', snippet: 'Information about station BSF.' },
  { path: 'time_stations/CHU.html', title: 'CHU - Signabroam Shortwave Wiki', snippet: 'Information about station CHU' },
  { path: 'time_stations/DCF77.html', title: 'DCF77 - Signabroam Shortwave Wiki', snippet: 'Information about station DCF77.' },
  { path: 'time_stations/HBG.html', title: 'HBG - Signabroam Shortwave Wiki', snippet: 'Information about station HBG.' },
  { path: 'time_stations/HLA.html', title: 'HLA - Signabroam Shortwave Wiki', snippet: 'Information about station HLA.' },
  { path: 'time_stations/JJY_hf.html', title: 'JJY (HF) - Signabroam Shortwave Wiki', snippet: 'Information about station JJY (HF).' },
  { path: 'time_stations/JJY_lf.html', title: 'JJY (LF) - Signabroam Shortwave Wiki', snippet: 'Information about station JJY (LF).' },
  { path: 'time_stations/LOL.html', title: 'LOL - Signabroam Shortwave Wiki', snippet: 'Information about station LOL.' },
  { path: 'time_stations/MSF.html', title: 'MSF - Signabroam Shortwave Wiki', snippet: 'Information about station MSF.' },
  { path: 'time_stations/RBU.html', title: 'RBU - Signabroam Shortwave Wiki', snippet: 'Information about station RBU.' },
  { path: 'time_stations/RWM.html', title: 'RWM - Signabroam Shortwave Wiki', snippet: 'Information about station RWM' },
  { path: 'time_stations/YVTO.html', title: 'YVTO - Signabroam Shortwave Wiki', snippet: 'Information about station YVTO.' },
  { path: 'time_stations/wwv.html', title: 'WWV - Signabroam Shortwave Wiki', snippet: 'Information about station WWV' },
  { path: 'time_stations/wwvb.html', title: 'WWVB - Signabroam Shortwave Wiki', snippet: 'Information about station WWVB' },
  { path: 'time_stations/wwvh.html', title: 'WWVH - Signabroam Shortwave Wiki', snippet: 'Information about station WWVH' },
  { path: 'us_military/cothen.html', title: 'COTHEN', snippet: 'Information about the Customs Over The Horizon Enforcement Network (COTHEN).' },
  { path: 'us_military/hfgcs.html', title: 'HF Global Communication System', snippet: 'Information about the HF Global Communication System (HFGCS) used by the United States Military.' },
  { path: 'us_military/shares.html', title: 'SHARES', snippet: 'Information about the Shared Resources HF Radio Program (SHARES).' },
  { path: 'us_military/us_navy_mars.html', title: 'US Navy MARS / Navy HF Networks', snippet: 'Information about US Navy MARS and Navy HF Networks used by the United States Navy.' },
  { path: 'us_military/usaf_ghfs.html', title: 'USAF Global High Frequency System', snippet: 'Information about the USAF Global High Frequency System (GHFS).' },
  { path: 'usa.html', title: 'United States Military', snippet: 'Information and resources about the United States Military.' },
];