window.siteSearchIndex = [
  { path: 'index.html', title: 'Signabroam Shortwave Wiki', snippet: 'Welcome to the Signabroam Shortwave Wiki. This wiki is dedicated to providing information and resources about shortwave radio.' },
  { path: 'rusmil.html', title: 'Russian Military', snippet: 'Russian military shortwave communications and stations' },
  { path: 'usa.html', title: 'United States Military', snippet: 'United States military shortwave radio frequencies and operations' },
  { path: 'asia.html', title: 'Asian Military', snippet: 'Asian military shortwave communications and stations' },
  { path: 'europe.html', title: 'European Military', snippet: 'European military shortwave radio operations' },
  { path: 'pirate.html', title: 'Pirate Stations', snippet: 'Pirate radio stations and unlicensed transmitters' },
  { path: 'military/03394.html', title: 'Station 03394', snippet: 'Russian military station information' },
  { path: 'military/14108.html', title: 'Station 14108', snippet: 'Russian military station information' },
  { path: 'military/3027.html', title: 'Station 3027', snippet: 'Russian military station information' },
  { path: 'military/31895.html', title: 'Station 31895', snippet: 'Russian military station information' },
  { path: 'military/32982.html', title: 'Station 32982', snippet: 'Russian military station information' },
  { path: 'military/34017.html', title: 'Station 34017', snippet: 'Russian military station information' },
  { path: 'military/41516.html', title: 'Station 41516', snippet: 'Russian military station information' },
  { path: 'military/43431.html', title: 'Station 43431', snippet: 'Russian military station information' },
  { path: 'military/49383.html', title: 'Station 49383', snippet: 'Russian military station information' },
  { path: 'military/52015.html', title: 'Station 52015', snippet: 'Russian military station information' },
  { path: 'military/52478.html', title: 'Station 52478', snippet: 'Russian military station information' },
  { path: 'military/52929.html', title: 'Station 52929', snippet: 'Russian military station information' },
  { path: 'military/5583.html', title: 'Station 5583', snippet: 'Russian military station information' },
  { path: 'military/56202.html', title: 'Station 56202', snippet: 'Russian military station information' },
  { path: 'military/56653.html', title: 'Station 56653', snippet: 'Russian military station information' },
  { path: 'military/59802.html', title: 'Station 59802', snippet: 'Russian military station information' },
  { path: 'military/71380.html', title: 'Station 71380', snippet: 'Russian military station information' },
  { path: 'military/73570.html', title: 'Station 73570', snippet: 'Russian military station information' },
  { path: 'military/77073.html', title: 'Station 77073', snippet: 'Russian military station information' },
  { path: 'military/83320.html', title: 'Station 83320', snippet: 'Russian military station information' },
  { path: 'military/95043.html', title: 'Station 95043', snippet: 'Russian military station information' },
  { path: 'military/airhorn.html', title: 'Airhorn', snippet: 'Russian military station' },
  { path: 'military/alarm.html', title: 'Alarm', snippet: 'Russian military alarm system' },
  { path: 'military/arbat50.html', title: 'Arbat-50', snippet: 'Russian military communications' },
  { path: 'military/baron78.html', title: 'Baron-78', snippet: 'Russian military station' },
  { path: 'military/bereza2.html', title: 'Bereza-2', snippet: 'Russian military communications' },
  { path: 'military/berkut24.html', title: 'Berkut-24', snippet: 'Russian military station' },
  { path: 'military/buzzer.html', title: 'Buzzer', snippet: 'Russian military beacon' },
  { path: 'military/davlenie.html', title: 'Davlenie', snippet: 'Russian military station' },
  { path: 'military/dmarker.html', title: 'D-Marker', snippet: 'Russian military direction marker' },
  { path: 'military/duplet16.html', title: 'Duplet-16', snippet: 'Russian military communications' },
  { path: 'military/dynatron.html', title: 'Dynatron', snippet: 'Russian military station' },
  { path: 'military/fgkt.html', title: 'FGKT', snippet: 'Russian military communications' },
  { path: 'military/goose.html', title: 'Goose', snippet: 'Russian military station' },
  { path: 'military/goretz81.html', title: 'Goretz-81', snippet: 'Russian military communications' },
  { path: 'military/kasta.html', title: 'Kasta', snippet: 'Russian military station' },
  { path: 'military/katok65.html', title: 'Katok-65', snippet: 'Russian military communications' },
  { path: 'military/kerropip.html', title: 'Kerro Pip Network', snippet: 'Russian military network' },
  { path: 'military/klarnetist.html', title: 'Klarnetist', snippet: 'Russian military musician network' },
  { path: 'military/korsar.html', title: 'Korsar', snippet: 'Russian military station' },
  { path: 'military/kroket21.html', title: 'Kroket-21', snippet: 'Russian military communications' },
  { path: 'military/lad-ya.html', title: 'Lad-Ya', snippet: 'Russian military station' },
  { path: 'military/magnetron.html', title: 'Magnetron', snippet: 'Russian military station' },
  { path: 'military/mikron79.html', title: 'Mikron-79', snippet: 'Russian military communications' },
  { path: 'military/nrn.html', title: 'Northern Russian Network', snippet: 'Russian military network' },
  { path: 'military/patron79.html', title: 'Patron-79', snippet: 'Russian military communications' },
  { path: 'military/Pikhta26.html', title: 'Pikhta-26', snippet: 'Russian military communications' },
  { path: 'military/pip.html', title: 'Pip', snippet: 'Russian military station' },
  { path: 'military/platoon.html', title: 'Platoon', snippet: 'Russian military station' },
  { path: 'military/polis.html', title: 'Polis', snippet: 'Russian military station' },
  { path: 'military/polotno.html', title: 'Polotno', snippet: 'Russian military communications' },
  { path: 'military/proselok.html', title: 'Proselok', snippet: 'Russian military station' },
  { path: 'military/rmarker.html', title: 'R-Marker', snippet: 'Russian military direction marker' },
  { path: 'military/s12035.html', title: 'S-12035', snippet: 'Russian military station' },
  { path: 'military/s39504960.html', title: 'S-39504960', snippet: 'Russian military communications' },
  { path: 'military/S4467.html', title: 'S-4467', snippet: 'Russian military station' },
  { path: 'military/s5959.html', title: 'S-5959', snippet: 'Russian military station' },
  { path: 'military/s9062.html', title: 'S-9062', snippet: 'Russian military station' },
  { path: 'military/sosna2.html', title: 'Sosna-2', snippet: 'Russian military communications' },
  { path: 'military/squeakywheel.html', title: 'Squeaky Wheel', snippet: 'Russian military station' },
  { path: 'military/srn.html', title: 'Southern Russian Network', snippet: 'Russian military network' },
  { path: 'military/tmarker.html', title: 'T-Marker', snippet: 'Russian military direction marker' },
  { path: 'military/topol.html', title: 'Topol', snippet: 'Russian military missile system' },
  { path: 'military/torez91.html', title: 'Torez-91', snippet: 'Russian military communications' },
  { path: 'military/vega.html', title: 'Vega', snippet: 'Russian military station' },
  { path: 'military/vetka31.html', title: 'Vetka-31', snippet: 'Russian military communications' },
  { path: 'military/zaliv52.html', title: 'Zaliv-52', snippet: 'Russian military communications' },
  { path: 'military/vcpt.html', title: 'Voice Communication Propagation Test', snippet: 'Russian Military Communication and Propagation Test' },
  { path: 'military/xlwf.html', title: 'Russian XM Whales Feedback', snippet: 'Russian Military Network' },
  { path: 'military/musicalpip.html', title: 'Russian Musical Pip', snippet: 'Russian Military Network' },
  { path: 'asian_military/vc01.html', title: 'VC01', snippet: 'Numbers Station' },
  { path: 'asian_military/xsl.html', title: 'XSL', snippet: 'Asian military defence' },
  { path: 'eu_military/d4285.html', title: 'D-4285', snippet: 'European military station' },
  { path: 'eu_military/ndh.html', title: 'NDH', snippet: 'European military communications' },
  { path: 'eu_military/obtb.html', title: 'OBTB', snippet: 'European military station' },
  { path: 'eu_military/pbb.html', title: 'PBB', snippet: 'European military communications' },
  { path: 'eu_military/pbb4285.html', title: 'PBB-4285', snippet: 'European military station' },
  { path: 'eu_military/pbbpcb-warship.html', title: 'PBB PCB Warship', snippet: 'European military naval communications' },
  { path: 'eu_military/pbv.html', title: 'PBV', snippet: 'European military station' },
  { path: 'eu_military/pcb.html', title: 'PCB', snippet: 'European military communications' },
  { path: 'eu_military/pcb4285.html', title: 'PCB-4285', snippet: 'European military station' },
  { path: 'eu_military/pjc.html', title: 'PJC', snippet: 'European military communications' },
  { path: 'eu_military/pjk.html', title: 'PJK', snippet: 'European military station' },
  { path: 'eu_military/unid13550.html', title: 'UNID-13550', snippet: 'European military unidentified station' },
  { path: 'eu_military/fav22.html', title: 'FAV22', snippet: 'French Morse station' },
  { path: 'eu_military/f9tm.html', title: 'F9TM', snippet: 'French Morse station' },
  { path: 'pirate/4525.html', title: '4525', snippet: 'Pirate radio station' },
  { path: 'pirate/akula56.html', title: 'Akula-56', snippet: 'Pirate station' },
  { path: 'pirate/m4j.html', title: 'M4J - Mystery for Joy', snippet: 'Pirate radio station' },
  { path: 'pirate/radiozand.html', title: 'Radiozand', snippet: 'Pirate radio station' },
  { path: 'pirate/rojxam.html', title: 'Rojxam', snippet: 'Pirate station' },
  { path: 'pirate/tsvef.html', title: 'Tsvef', snippet: 'Pirate radio station' },
  { path: 'pirate/starlight.html', title: 'Radio Starlight', snippet: 'Pirate radio station' },
  { path: 'pirate/pamela.html', title: 'Radio Pamela', snippet: 'Pirate radio station' },
  { path: 'pirate/stern.html', title: 'Radio Stern', snippet: 'Pirate radio station' },
  { path: 'pirate/argus.html', title: 'Radio Argus', snippet: 'Pirate radio station' },
  { path: 'pirate/6660.html', title: 'The 45m Band', snippet: 'Pirate radio station' },
  { path: 'pirate/miamigo.html', title: 'Radio Mi Amigo International', snippet: 'Pirate radio station' },
  { path: 'pirate/rwi.html', title: 'Radio Wave International', snippet: 'Pirate radio station' },
  { path: 'pirate/zeppelin.html', title: 'Radio Zeppelin', snippet: 'Pirate radio station' },
  { path: 'pirate/augusta.html', title: 'Radio Augusta International', snippet: 'Pirate radio station' },
  { path: 'us_military/hfgcs.html', title: 'HFGCS', snippet: 'US military High Frequency Global Communications System' },
  { path: 'more/bandplan.html', title: 'Band Plan', snippet: 'Radio frequency band plan and allocations' },
  { path: 'more/ids.html', title: 'Station IDs', snippet: 'Information about station ID system' },
  { path: 'more/stationschedule.html', title: 'Station Schedule', snippet: 'Schedule of broadcast times for stations' },
  { path: 'numbers-stations.html', title: 'Numbers Stations', snippet: 'List of Numbers Stations around the world' },
  { path: 'numbers-stations/morse/fl.html', title: 'FL Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/morse/msk.html', title: 'MSK Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/morse/ici.html', title: 'ICI Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/english/e06.html', title: 'E06 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/morse/m14.html', title: 'M14 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/morse/m01.html', title: 'M01 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/morse/m12.html', title: 'M12 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/morse/m23.html', title: 'M23 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/english/e07.html', title: 'E07 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/other/v07.html', title: 'V07 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/other/v07f.html', title: 'V07f Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/polytone/xpa.html', title: 'XPA Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/polytone/xpa2.html', title: 'XPA2 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/polytone/xpb.html', title: 'XPB Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/digital/f07.html', title: 'F07 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/digital/p07.html', title: 'P07 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/german/g07.html', title: 'G07 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/slavic/s07.html', title: 'S07 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/polytone/xp.html', title: 'XP Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/slavic/s06.html', title: 'S06 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/digital/f01.html', title: 'F01 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/digital/f06.html', title: 'F06 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/english/e17.html', title: 'E17 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/german/g06.html', title: 'G06 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/other/v06.html', title: 'V06 Number Station', snippet: 'Numbers Stations' },
  { path: 'numbers-stations/other/v23.html', title: 'V23 Number Station', snippet: 'Numbers Stations' },
  { path: 'modems.html', title: 'Worldwide Modems', snippet: 'Modems around the World'},
  { path: 'modems/cis3.html', title: 'CIS-3 Modem', snippet: 'Russian 3 Tones Circuit modem'},
  { path: 'modems/cis12.html', title: 'CIS-12 Modem', snippet: 'Russian 12 Tones modem, also called AT-3004D / AT-3104D / FIRE.'},
  { path: 'modems/cis112.html', title: 'CIS-112', snippet: 'Russian 112 Tones OFDM modem'}
];
